stages:
- name: Build & Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./dockerfile
      buildContext: .
      tag: redis-test:${CICD_EXECUTION_SEQUENCE}
    env:
      PLUGIN_MTU: "1450"
  when:
    branch: {}
    event:
      include:
      - push
      - pull request
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./redis-test-dc.yaml
  when:
    branch: {}
    event:
      include:
      - push
      - pull request
branch:
  include:
  - master
notification: {}
