stages:
- name: Build & Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./dockerfile
      buildContext: .
      tag: redis-test:${CICD_EXECUTION_SEQUENCE}
    env:
      PLUGIN_MTU: 1450
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./redis-test-dc.yaml