apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-test
  namespace: redis-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-test
  template:
    metadata:
      labels:
        app: redis-test
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: redis-test
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: Always
        env:
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              key: REDIS_PASS
              name: redis-pass
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              key: REDIS_HOST
              name: redis-pass